### ISSUE TITLE
Combine watch tasks

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-repo-tools#11]
For News, we have to run each of these watch tasks seperately:

* `yarn workspace run start` for the theme `start`
* `npm run sync` for browsersync
* `npm run start` for wporg-mu-plugins

It'd be more convenient if a `yarn workshop run start` would run the other two commands, and display their output alongside the output for the theme's `start` command.

It seems like setting up a workspace for `wporg-mu-plugins` would fix that one, but I tried that and it didn't seem to work. I'm not sure how to do it for browsersync off the top of my head, but I'm guessing there's a way.

**Comment by coreymckrill** [comment]
News already has `wporg-mu-plugins` set up [as a workspace](https://github.com/WordPress/wporg-news-2021/blob/trunk/package.json#L28). I've been able to run `yarn workspaces run start` successfully...

**Comment by iandunn** [comment]
Yeah, I left it in there, but when I run it, it only runs the theme `start`, not the mu-plugins `start`.

Does it run both for you?

**Comment by coreymckrill** [comment]
🤔 Hmm, looks like it only runs the theme for me as well. Both work when I run `yarn workspaces run build`, though.

Maybe it has something to do with using chokidar instead of wp-scripts for the watch functionality...
